# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - naotimetrack

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '10.14'

    - name: npm install, build, and test
      run: |
        npm install -g grunt bower
        npm install
        bower install
        grunt build

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'naotimetrack'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_48d4955387a74dda9352ab3d5d03537f }}
        package: .